RallyHelper/WebApp/Pages/Items/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using DAL;
using Domain;

namespace WebApp.Pages.Items
{
    public class CreateModel : PageModel
    {
        private readonly DAL.AppDbContext _context;

        public CreateModel(DAL.AppDbContext context)
        {
            _context = context;
        }

        public IActionResult OnGet()
        {
        ViewData["CategoryId"] = new SelectList(_context.ItemCategories, "Id", "CategoryName");
        ViewData["LocationId"] = new SelectList(_context.ItemLocations, "Id", "LocationName");
            return Page();
        }

        [BindProperty]
        public Item Item { get; set; } = default!;
        

        // To protect from overposting attacks, see https://aka.ms/RazorPagesCRUD
        public async Task<IActionResult> OnPostAsync()
        {
          if (!ModelState.IsValid || _context.Items == null || Item == null)
            {
                return Page();
            }

            _context.Items.Add(Item);
            await _context.SaveChangesAsync();

            return RedirectToPage("./Index");
        }
    }
}

RallyHelper/WebApp/Pages/Items/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using DAL;
using Domain;

namespace WebApp.Pages.Items
{
    public class DeleteModel : PageModel
    {
        private readonly DAL.AppDbContext _context;

        public DeleteModel(DAL.AppDbContext context)
        {
            _context = context;
        }

        [BindProperty]
      public Item Item { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null || _context.Items == null)
            {
                return NotFound();
            }

            var item = await _context.Items.FirstOrDefaultAsync(m => m.Id == id);

            if (item == null)
            {
                return NotFound();
            }
            else 
            {
                Item = item;
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(int? id)
        {
            if (id == null || _context.Items == null)
            {
                return NotFound();
            }
            var item = await _context.Items.FindAsync(id);

            if (item != null)
            {
                Item = item;
                _context.Items.Remove(Item);
                await _context.SaveChangesAsync();
            }

            return RedirectToPage("./Index");
        }
    }
}

RallyHelper/WebApp/Pages/Items/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using DAL;
using Domain;

namespace WebApp.Pages.Items
{
    public class DetailsModel : PageModel
    {
        private readonly DAL.AppDbContext _context;

        public DetailsModel(DAL.AppDbContext context)
        {
            _context = context;
        }

      public Item Item { get; set; } = default!; 

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null || _context.Items == null)
            {
                return NotFound();
            }

            var item = await _context.Items.FirstOrDefaultAsync(m => m.Id == id);
            if (item == null)
            {
                return NotFound();
            }
            else 
            {
                Item = item;
            }
            return Page();
        }
    }
}

RallyHelper/WebApp/Pages/Items/Edit.cshtml.cs
using Domain;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

public class EditModel : PageModel
{
    private readonly DAL.AppDbContext _context;

    public EditModel(DAL.AppDbContext context)
    {
        _context = context;
    }

    [BindProperty]
    public Item Item { get; set; } = default!;

    public async Task<IActionResult> OnGetAsync(int? id)
    {
        if (id == null || _context.Items == null)
        {
            return NotFound();
        }

        var item = await _context.Items.FirstOrDefaultAsync(m => m.Id == id);
        if (item == null)
        {
            return NotFound();
        }
        Item = item;
        return Page();
    }

    public async Task<IActionResult> OnPostAsync()
    {

        var itemToUpdate = await _context.Items.FirstOrDefaultAsync(i => i.Id == Item.Id);
        if (itemToUpdate == null)
        {
            return NotFound();
        }

        itemToUpdate.CurrentQuantity = Item.CurrentQuantity; // Update only the CurrentQuantity

        try
        {
            await _context.SaveChangesAsync();
        }
        catch (DbUpdateConcurrencyException)
        {
            if (!ItemExists(Item.Id))
            {
                return NotFound();
            }
            else
            {
                throw;
            }
        }

        TempData["Updated"] = true;
        return RedirectToPage("./Index", new { update = DateTime.Now.Ticks });
    }

    private bool ItemExists(int id)
    {
        return (_context.Items?.Any(e => e.Id == id)).GetValueOrDefault();
    }
}

RallyHelper/WebApp/Pages/Jobs/AddItemToJob.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using DAL;
using System.Threading.Tasks;
using Domain;
using Microsoft.EntityFrameworkCore;

namespace WebApp.Pages.Jobs;

public class AddItemToJobModel : PageModel
{
    private readonly AppDbContext _context;

    public AddItemToJobModel(AppDbContext context)
    {
        _context = context;
    }

    [BindProperty(SupportsGet = true)]
    public int ItemId { get; set; }

    [BindProperty(SupportsGet = true)]
    public int JobId { get; set; }

    [BindProperty]
    public int Quantity { get; set; }
    
    [BindProperty]
    public int MaxAvailableQuantity { get; set; }

    public async Task OnGetAsync()
    {
        Console.WriteLine("Hello from get on add item");
        var item = await _context.Items
            .Where(i => i.Id == ItemId)
            .FirstOrDefaultAsync();
        MaxAvailableQuantity = item?.CurrentQuantity ?? 0;
    }
    
    public async Task<IActionResult> OnPostAsync()
    {
        // Check if the job and item exist
        var jobExists = await _context.Jobs.AnyAsync(j => j.Id == JobId);
        var itemExists = await _context.Items.AnyAsync(i => i.Id == ItemId);

        if (jobExists && itemExists && Quantity > 0)
        {
            var jobItem = new JobItem
            {
                JobId = JobId,
                ItemId = ItemId,
                NeededQuantity = Quantity
            };

            _context.JobItems.Add(jobItem);
            await _context.SaveChangesAsync();
            TempData["SuccessMessage"] = $"Item added to job successfully.";
        }
        else
        {
            TempData["ErrorMessage"] = "Error: Invalid job or item, or quantity is zero.";
        }

        return RedirectToPage("/Jobs/AddJobComponents", new { jobId = JobId });
    }

}

RallyHelper/WebApp/Pages/Jobs/AddJobComponents.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using DAL;
using Domain;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;

namespace WebApp.Pages.Jobs;

public class AddJobComponents : PageModel
{
    private readonly AppDbContext _context;

    public AddJobComponents(AppDbContext context)
    {
        _context = context;
    }

    [BindProperty(SupportsGet = true)]
    public int JobId { get; set; }
    
    [BindProperty(SupportsGet = true)]
    public string SelectedItemName { get; set; }

    [BindProperty(SupportsGet = true)]
    public int? SelectedCategoryId { get; set; }

    [BindProperty(SupportsGet = true)]
    public int? SelectedLocationId { get; set; }

    [BindProperty(SupportsGet = true)]
    public int? NeededQuantity { get; set; }

    public SelectList ItemNameOptions { get; set; }
    public SelectList CategoryOptions { get; set; }
    public SelectList LocationOptions { get; set; }

    public List<Item> FilteredItems { get; set; }

    private async Task PopulateDropdowns()
    {
        ItemNameOptions = new SelectList(await _context.Items.Select(i => i.ItemName).Distinct().ToListAsync(), "", "");
        CategoryOptions = new SelectList(await _context.ItemCategories.ToListAsync(), "Id", "CategoryName");
        LocationOptions = new SelectList(await _context.ItemLocations.ToListAsync(), "Id", "LocationName");
    }

    public async Task OnGetAsync()
    {
        await PopulateDropdowns();
        await ApplyFilters();
    }

    private async Task ApplyFilters()
    {
        IQueryable<Item> query = _context.Items.Include(i => i.Category).Include(i => i.Location);

        if (!string.IsNullOrEmpty(SelectedItemName))
            query = query.Where(i => i.ItemName == SelectedItemName);
        if (SelectedCategoryId.HasValue)
            query = query.Where(i => i.CategoryId == SelectedCategoryId.Value);
        if (SelectedLocationId.HasValue)
            query = query.Where(i => i.LocationId == SelectedLocationId.Value);
        if (NeededQuantity.HasValue)
            query = query.Where(i => i.CurrentQuantity >= NeededQuantity.Value);

        FilteredItems = await query.ToListAsync();
    }

    public async Task<IActionResult> OnPostAsync()
    {
        await PopulateDropdowns();
        await ApplyFilters();

        return Page();
    }

    public async Task<IActionResult> OnPostClearFiltersAsync()
    {
        return RedirectToPage(new { SelectedItemName = "", SelectedCategoryId = (int?)null, SelectedLocationId = (int?)null, NeededQuantity = (int?)null });
    }
    
    public IActionResult OnPostRedirectToReview(int jobId)
    {
        return RedirectToPage("/Jobs/ReviewOrder", new { jobId = jobId });
    }
}

RallyHelper/WebApp/Pages/Jobs/Create.cshtml.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using DAL;
using Domain;

namespace WebApp.Pages.Jobs
{
    public class CreateModel : PageModel
    {
        private readonly AppDbContext _context;

        public CreateModel(AppDbContext context)
        {
            _context = context;
        }

        public bool HasActiveRally { get; set; }

        public void OnGet()
        {
            HasActiveRally = _context.Rallies.Any(r => r.EndTime == null || r.EndTime > DateTime.Now);
        }

        [BindProperty]
        public string ClientName { get; set; }

        public async Task<IActionResult> OnPostAsync()
        {
            if (string.IsNullOrEmpty(ClientName))
            {
                return Page();
            }

            // Find the active rally
            var activeRally = _context.Rallies
                .FirstOrDefault(r => r.StartTime <= DateTime.Now && 
                                     (r.EndTime == null || r.EndTime > DateTime.Now));

            if (activeRally == null)
            {
                TempData["Message"] = "No active rally available. Cannot create a job.";
                return RedirectToPage();
            }

            var job = new Job
            {
                ClientName = ClientName,
                RallyId = activeRally.Id 
                // Other properties remain null initially
            };

            _context.Jobs.Add(job);
            await _context.SaveChangesAsync();

            // Redirect to the next step with the job's ID
            return RedirectToPage("/Jobs/AddJobComponents", new { jobId = job.Id });
        }

    }
}

RallyHelper/WebApp/Pages/Jobs/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using DAL;
using Domain;

namespace WebApp.Pages.Jobs
{
    public class DetailsModel : PageModel
    {
        private readonly DAL.AppDbContext _context;

        public DetailsModel(DAL.AppDbContext context)
        {
            _context = context;
        }

      public Job Job { get; set; } = default!; 

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null || _context.Jobs == null)
            {
                return NotFound();
            }

            var job = await _context.Jobs.FirstOrDefaultAsync(m => m.Id == id);
            if (job == null)
            {
                return NotFound();
            }
            else 
            {
                Job = job;
            }
            return Page();
        }
    }
}

RallyHelper/WebApp/Pages/Jobs/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using DAL;
using Domain;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;

namespace WebApp.Pages.Jobs
{
    public class IndexModel : PageModel
    {
        private readonly AppDbContext _context;

        public IndexModel(AppDbContext context)
        {
            _context = context;
        }

        public IList<Job> Job { get; set; } = default!;
        public bool IsAdmin { get; set; } = false; 

        public async Task OnGetAsync()
        {
            IsAdmin = HttpContext.Session.GetString("IsAdmin") == "true"; // Determine if the user is an admin

            if (_context.Jobs != null)
            {
                Job = await _context.Jobs
                    .Include(j => j.JobItems)
                    .ThenInclude(ji => ji.Item)
                    .ThenInclude(i => i.Category)
                    .Include(j => j.JobItems)
                    .ThenInclude(ji => ji.Item)
                    .ThenInclude(i => i.Location)
                    .ToListAsync();
            }
        }

        public async Task<IActionResult> OnPostMarkAsClosedAsync(int jobId)
        {
            var job = await _context.Jobs.FindAsync(jobId);
            if (job != null && job.EndTime == null)
            {
                job.EndTime = DateTime.Now;
                await _context.SaveChangesAsync();
            }

            return RedirectToPage();
        }
    }
}

RallyHelper/WebApp/Pages/Jobs/ReviewOrder.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using DAL;
using Domain;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;

namespace WebApp.Pages.Jobs;

public class ReviewOrder : PageModel
{
    private readonly AppDbContext _context;

    public ReviewOrder(AppDbContext context)
    {
        _context = context;
    }

    [BindProperty(SupportsGet = true)]
    public int JobId { get; set; }

    public List<JobItem> JobItems { get; set; }

    public decimal TotalPrice { get; set; }

    public async Task OnGetAsync()
    {
        JobItems = await _context.JobItems
            .Where(ji => ji.JobId == JobId)
            .Include(ji => ji.Item)
            .ToListAsync();

        // Calculate the total price
        TotalPrice = JobItems.Sum(ji => ji.Item.PricePerItem * ji.NeededQuantity);
    }

    public async Task<IActionResult> OnPostDeleteAsync(int itemId)
    {
        var jobItem = await _context.JobItems
            .FirstOrDefaultAsync(ji => ji.JobId == JobId && ji.ItemId == itemId);

        if (jobItem != null)
        {
            _context.JobItems.Remove(jobItem);
            await _context.SaveChangesAsync();
        }

        return RedirectToPage(new { jobId = JobId });
    }
    
    public async Task<IActionResult> OnPostPlaceOrderAsync()
    {
        var job = await _context.Jobs.Include(j => j.JobItems).ThenInclude(ji => ji.Item).FirstOrDefaultAsync(j => j.Id == JobId);

        // Check if all items have sufficient quantity in stock
        foreach (var jobItem in job.JobItems)
        {
            if (jobItem.Item.CurrentQuantity < jobItem.NeededQuantity)
            {
                TempData["ErrorMessage"] = $"Insufficient stock for item: {jobItem.Item.ItemName}.";
                return RedirectToPage(new { jobId = JobId });
            }
        }

        // Deduct the quantity from stock and calculate the total price
        decimal totalPrice = 0;
        foreach (var jobItem in job.JobItems)
        {
            jobItem.Item.CurrentQuantity -= jobItem.NeededQuantity;
            totalPrice += jobItem.Item.PricePerItem * jobItem.NeededQuantity;
        }

        // Update job details and save changes
        job.StartTime = DateTime.Now;
        job.TotalPrice = totalPrice;
        await _context.SaveChangesAsync();

        return RedirectToPage("/Jobs/Index");
    }

}

RallyHelper/WebApp/Pages/Jobs/AddItemToJob.cshtml
@page "{itemId:int}/{jobId:int}"
@model WebApp.Pages.Jobs.AddItemToJobModel

@{
    ViewData["Title"] = "Add Item to Job";
}

<h2>Add Item to Job</h2>

<form method="post">
    <input type="hidden" asp-for="ItemId" />
    <input type="hidden" asp-for="JobId" />
    <div class="form-group">
        <label for="quantity">Quantity</label>
        <select asp-for="Quantity" class="form-control">
            @for (int i = 1; i <= Model.MaxAvailableQuantity; i++)
            {
                <option value="@i">@i</option>
            }
        </select>
    </div>
    <button type="submit" class="btn btn-primary">Add to Job</button>
</form>

RallyHelper/WebApp/Pages/Jobs/AddJobComponents.cshtml
@page
@model WebApp.Pages.Jobs.AddJobComponents

@{
    ViewData["Title"] = "Add Job Components";
}

@if (TempData["SuccessMessage"] != null)
{
    <div class="alert alert-success">
        @TempData["SuccessMessage"]
    </div>
}

@if (TempData["ErrorMessage"] != null)
{
    <div class="alert alert-danger">
        @TempData["ErrorMessage"]
    </div>
}

<h2>Adding Job Components</h2>

<form method="post">
    <div class="form-group">
        <label for="selectedItemName">Item Name</label>
        <select asp-for="SelectedItemName" asp-items="Model.ItemNameOptions" class="form-control">
            <option value="">-- Select Item --</option>
        </select>
    </div>
    <div class="form-group">
        <label for="selectedCategoryId">Category</label>
        <select asp-for="SelectedCategoryId" asp-items="Model.CategoryOptions" class="form-control">
            <option value="">-- Select Category --</option>
        </select>
    </div>
    <div class="form-group">
        <label for="selectedLocationId">Location</label>
        <select asp-for="SelectedLocationId" asp-items="Model.LocationOptions" class="form-control">
            <option value="">-- Select Location --</option>
        </select>
    </div>
    <div class="form-group">
        <label for="neededQuantity">Needed Quantity</label>
        <input type="number" asp-for="NeededQuantity" class="form-control"/>
    </div>
    <div class="form-group">
        <button type="submit" class="btn btn-primary">Search</button>
        <button type="submit" class="btn btn-secondary" asp-page-handler="ClearFilters">Clear Filters</button>
    </div>
</form>

@if (Model.FilteredItems != null && Model.FilteredItems.Any())
{
    <table class="table mt-4">
        <thead>
        <tr>
            <th>Name</th>
            <th>Category</th>
            <th>Location</th>
            <th>Available Quantity</th>
            <th>Price per item</th>
        </tr>
        </thead>
        <tbody>
        @foreach (var item in Model.FilteredItems)
        {
            <tr>
                <td>@item.ItemName</td>
                <td>@item.Category.CategoryName</td>
                <td>@item.Location.LocationName</td> 
                <td>@item.CurrentQuantity</td>
                <td>@item.PricePerItem</td>
                <td>
                    <a asp-page="/Jobs/AddItemToJob" asp-route-itemId="@item.Id" asp-route-jobId="@Model.JobId" class="btn btn-primary">Add to Order</a>
                </td>
            </tr>
        }
        </tbody>
    </table>
    <form method="post" asp-page-handler="RedirectToReview">
        <input type="hidden" name="jobId" value="@Model.JobId" />
        <button type="submit" class="btn btn-primary">Proceed to review</button>
    </form>

}

RallyHelper/WebApp/Pages/Jobs/Create.cshtml
@page
@model WebApp.Pages.Jobs.CreateModel

@{
    ViewData["Title"] = "Create Job";
}

<h1>Create Job</h1>

@if (Model.HasActiveRally)
{
    <form method="post">
        <div class="form-group">
            <label for="clientName">Please enter your name</label>
            <input type="text" class="form-control" id="clientName" name="ClientName" required />
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
}
else
{
    <div class="alert alert-warning">
        Sorry, there is no active rally now, which means we're currently closed. Please come back later.
    </div>
}

<div>
    <a asp-page="/Shared/Index">Go back</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

RallyHelper/WebApp/Pages/Jobs/Delete.cshtml
@page
@model WebApp.Pages.Jobs.DeleteModel

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Job</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Job.TotalPrice)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Job.TotalPrice)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Job.StartTime)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Job.StartTime)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Job.EndTime)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Job.EndTime)
        </dd>
    </dl>
    
    <form method="post">
        <input type="hidden" asp-for="Job.Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-page="./Index">Back to List</a>
    </form>
</div>

RallyHelper/WebApp/Pages/Jobs/Details.cshtml
@page
@model WebApp.Pages.Jobs.DetailsModel

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Job</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Job.TotalPrice)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Job.TotalPrice)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Job.StartTime)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Job.StartTime)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Job.EndTime)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Job.EndTime)
        </dd>
    </dl>
</div>
<div>
    <a asp-page="./Edit" asp-route-id="@Model.Job?.Id">Edit</a> |
    <a asp-page="./Index">Back to List</a>
</div>

RallyHelper/WebApp/Pages/Jobs/Edit.cshtml
@page
@model WebApp.Pages.Jobs.EditModel

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Job</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Job.Id" />
            <div class="form-group">
                <label asp-for="Job.TotalPrice" class="control-label"></label>
                <input asp-for="Job.TotalPrice" class="form-control" />
                <span asp-validation-for="Job.TotalPrice" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Job.RallyId" class="control-label"></label>
                <select asp-for="Job.RallyId" class="form-control" asp-items="ViewBag.RallyId"></select>
                <span asp-validation-for="Job.RallyId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Job.StartTime" class="control-label"></label>
                <input asp-for="Job.StartTime" class="form-control" />
                <span asp-validation-for="Job.StartTime" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Job.EndTime" class="control-label"></label>
                <input asp-for="Job.EndTime" class="form-control" />
                <span asp-validation-for="Job.EndTime" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-page="./Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

RallyHelper/WebApp/Pages/Jobs/Index.cshtml
@page
@model WebApp.Pages.Jobs.IndexModel

@{
    ViewData["Title"] = "Jobs";
}

<h1>Jobs</h1>

<table class="table">
    <thead>
        <tr>
            <th>Client Name</th>
            <th>Total Price</th>
            <th>Status</th>
            <th>Item Details</th>
            @if (Model.IsAdmin)
            {
                <th>Actions</th>
            }
        </tr>
    </thead>
    <tbody>
    @foreach (var job in Model.Job)
    {
        <tr>
            <td>@job.ClientName</td>
            <td>@job.TotalPrice.ToString()</td>
            <td>
                @{
                    var status = job.EndTime != null ? "Closed" :
                                 job.StartTime != null ? "Active" : "Suspended";
                }
                @status
            </td>
            <td>
                @foreach (var item in job.JobItems)
                {
                    <p>@item.Item.ItemName - Qty: @item.NeededQuantity, Category: @item.Item.Category.CategoryName, Location: @item.Item.Location.LocationName</p>
                }
            </td>
            @if (Model.IsAdmin && status == "Active")
            {
                <td>
                    <form method="post" asp-page-handler="MarkAsClosed" asp-route-jobId="@job.Id">
                        <button type="submit" class="btn btn-primary">Mark as Closed</button>
                    </form>
                </td>
            }
        </tr>
    }
    </tbody>
</table>

RallyHelper/WebApp/Pages/Jobs/ReviewOrder.cshtml
@page "{jobId:int}"
@model WebApp.Pages.Jobs.ReviewOrder

@{
    ViewData["Title"] = "Review Order";
}

<h2>Review Order</h2>

@if (Model.JobItems != null && Model.JobItems.Count > 0)
{
    <table class="table">
        <thead>
        <tr>
            <th>Item Name</th>
            <th>Quantity</th>
            <th>Action</th>
        </tr>
        </thead>
        <tbody>
        @foreach (var item in Model.JobItems)
        {
            <tr>
                <td>@item.Item.ItemName</td>
                <td>@item.NeededQuantity</td>
                <td>
                    <form method="post" asp-page-handler="Delete" asp-route-itemId="@item.ItemId">
                        <input type="hidden" asp-for="JobId" />
                        <button type="submit" class="btn btn-danger">Delete from Order</button>
                    </form>
                </td>
            </tr>
        }
        </tbody>
    </table>
    
    <p>Total Price: @Model.TotalPrice.ToString("C")</p>

    <form method="post" asp-page-handler="PlaceOrder">
        <input type="hidden" asp-for="JobId" />
        <button type="submit" class="btn btn-success">Place Order</button>
    </form>

}
else
{
    <p>No items in the order.</p>
}

<a asp-page="/Jobs/AddJobComponents" asp-route-jobId="@Model.JobId" class="btn btn-primary">Add More Items</a>